version: "3"

services: 
    golang:
        build: .
        container_name: "redis-in-action-golang"
        tty: true
        volumes:
            - .:/src/app
        depends_on:
            - redis
        network_mode: "host"
    
    redis:
        image: redis:6.0-rc-alpine
        container_name: "redis-in-action-redis"
        ports: 
          - "6379:6379"
        expose:
          - "6379"
